[tool.poetry]
name = "tubex-replit"
version = "0.1.0"
description = "A simple way to use Tubex with Python online."
authors = ["Simon Rohou <simon.rohou@ensta-bretagne.fr>"]

[tool.poetry.dependencies]
python = "^3.8"
tubex-lib="^3.0.0b5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"